### ISSUE TITLE
Generacija Urnika Kluba

### ISSUE THREAD

**Issue by QuantumlyTangled** [QuantumlyTangled/ip-2020-2021#5]
Urnik bi lahko bila tabele narejena iz JSON objekta.
Zanimiva metoda tega bi bila uporaba DataTables.
[Primer lahko najdemo tukaj](https://datatables.net/forums/discussion/55238/is-there-an-example-showing-how-to-use-datatables-in-conjunction-with-django-models)

**Comment by franga2000** [comment]
Myb chill with the over-engineering and get to the MVP :sweat_smile: 

AJAX je unnecessary za to, ker bo itak triggered samo on load, razen če hočeš met week-by-week urnike. Če hočeš uporabljat datatable, best render a normal HTML table with Django and then run it on top of it. 

Če pa že hočeš met week-by-week urnike, je bolj pametno nekaj takega nardit s koledarjem ([FullCalendar](https://fullcalendar.io/docs/timegrid-view) za UI in po možnosti sync-in iz iCal linka za Google Calendar and whatever else they might use)
